-- Initial low-risk D1 schema slice.
-- IDs are generated by application code with crypto.randomUUID().
-- Timestamps are stored as UTC ISO-8601 text.
-- JSON values are stored as text and validated on write.

CREATE TABLE system_events (
  event_id TEXT PRIMARY KEY NOT NULL,
  event_type TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'success'
    CHECK (status IN ('success', 'error')),
  submission_id TEXT,
  public_token TEXT,
  source TEXT,
  metadata TEXT NOT NULL DEFAULT '{}'
    CHECK (json_valid(metadata)),
  created_at TEXT NOT NULL DEFAULT (
    strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
  )
);

CREATE INDEX system_events_created_at_idx
  ON system_events (created_at DESC);

CREATE INDEX system_events_event_type_idx
  ON system_events (event_type);

CREATE INDEX system_events_submission_id_idx
  ON system_events (submission_id);
