-- Dedicated baseline schema. Apply to QA only until separate production approval.
CREATE TABLE tb_baseline_versions (version TEXT PRIMARY KEY, definition_json TEXT NOT NULL CHECK(json_valid(definition_json)), created_at TEXT NOT NULL);
CREATE TABLE tb_baseline_campaigns (campaign_id TEXT PRIMARY KEY, name TEXT NOT NULL, version TEXT NOT NULL REFERENCES tb_baseline_versions(version), status TEXT NOT NULL CHECK(status IN ('draft','open','closed')), closes_at TEXT NOT NULL, privacy_notice TEXT NOT NULL, retention_days INTEGER NOT NULL CHECK(retention_days BETWEEN 30 AND 730), created_at TEXT NOT NULL);
CREATE TABLE tb_baseline_participants (participant_id TEXT PRIMARY KEY, campaign_id TEXT NOT NULL REFERENCES tb_baseline_campaigns(campaign_id), email TEXT NOT NULL, profile_json TEXT NOT NULL CHECK(json_valid(profile_json)), active INTEGER NOT NULL DEFAULT 1 CHECK(active IN (0,1)), created_at TEXT NOT NULL, UNIQUE(campaign_id,email));
CREATE TABLE tb_baseline_invites (invite_id TEXT PRIMARY KEY, participant_id TEXT NOT NULL REFERENCES tb_baseline_participants(participant_id), token_hash TEXT NOT NULL UNIQUE, expires_at TEXT NOT NULL, revoked_at TEXT, created_at TEXT NOT NULL);
CREATE TABLE tb_baseline_sessions (session_hash TEXT PRIMARY KEY, participant_id TEXT NOT NULL REFERENCES tb_baseline_participants(participant_id), invite_id TEXT NOT NULL REFERENCES tb_baseline_invites(invite_id), expires_at TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE tb_baseline_responses (participant_id TEXT PRIMARY KEY REFERENCES tb_baseline_participants(participant_id), version TEXT NOT NULL REFERENCES tb_baseline_versions(version), status TEXT NOT NULL CHECK(status IN ('not_started','in_progress','completed')), progress INTEGER NOT NULL DEFAULT 0 CHECK(progress BETWEEN 0 AND 8), revision INTEGER NOT NULL DEFAULT 0, mutation_id TEXT NOT NULL, draft_json TEXT NOT NULL CHECK(json_valid(draft_json)), updated_at TEXT NOT NULL, submitted_at TEXT);
CREATE TABLE tb_baseline_work (participant_id TEXT NOT NULL REFERENCES tb_baseline_responses(participant_id), area_code TEXT NOT NULL, label TEXT NOT NULL, category TEXT NOT NULL, pillar TEXT NOT NULL CHECK(pillar IN ('people_operations','business_partnering','people_technology')), percentage REAL CHECK(percentage BETWEEN 0 AND 100), detail_json TEXT NOT NULL CHECK(json_valid(detail_json)), PRIMARY KEY(participant_id,area_code));
CREATE TABLE tb_baseline_rate_limits (bucket_hash TEXT PRIMARY KEY, window_started_at TEXT NOT NULL, attempts INTEGER NOT NULL);
CREATE TABLE tb_baseline_audit (event_id TEXT PRIMARY KEY, campaign_id TEXT REFERENCES tb_baseline_campaigns(campaign_id), actor TEXT NOT NULL, action TEXT NOT NULL, subject_id TEXT, metadata_json TEXT NOT NULL CHECK(json_valid(metadata_json)), created_at TEXT NOT NULL);
CREATE INDEX tb_baseline_participants_campaign ON tb_baseline_participants(campaign_id);
CREATE INDEX tb_baseline_sessions_expiry ON tb_baseline_sessions(expires_at);
CREATE INDEX tb_baseline_invites_participant ON tb_baseline_invites(participant_id);
CREATE INDEX tb_baseline_audit_campaign ON tb_baseline_audit(campaign_id,created_at);
