export const ACTION_LABELS: Record<string, string> = {
  ops_01: "Answer employee questions",
  ops_02: "Prepare contracts and employee letters",
  ops_03: "Arrange steps when people join",
  ops_04: "Arrange steps when people leave",
  ops_05: "Update employee records",
  ops_06: "Manage leave and absence records",
  ops_07: "Enter or check payroll information",
  ops_08: "Help with employee benefits",
  ops_09: "Arrange documents and meetings for employee cases",
  ops_10: "Arrange interviews and hiring documents",
  ops_11: "Help with country moves and work permits",
  ops_12: "Complete required local employment administration",
  ops_13: "Prepare and check people reports",
  ops_14: "Write or explain policies and guidance",
  ops_15: "Handle People support requests and tickets",
  ops_16: "Coordinate external services and suppliers",
  ops_17: "Do other employee support or administration",
  ops_18: "Arrange employee events and activities",
  bp_01: "Advise and coach managers",
  bp_02: "Handle employee cases and give advice",
  bp_03: "Support agreed organisation changes",
  bp_04: "Plan staffing needs",
  bp_05: "Support goals and performance conversations",
  bp_06: "Support development and succession planning",
  bp_07: "Understand employee feedback and improve experience",
  bp_08: "Give input to pay and reward decisions",
  bp_09: "Work with managers on hiring needs",
  bp_10: "Help people understand and implement changes",
  bp_11: "Interpret people data for the business",
  bp_12: "Support local consultation and people decisions",
  bp_13: "Do employee administration alongside manager advice",
  bp_14: "Do other manager or business support",
  tech_01: "Maintain a People system",
  tech_02: "Change system settings and forms",
  tech_03: "Help people use systems and solve problems",
  tech_04: "Connect systems and move information between them",
  tech_05: "Build workflows and automate steps",
  tech_06: "Use or develop AI and digital tools",
  tech_07: "Check and improve information in systems",
  tech_08: "Build reports and dashboards",
  tech_09: "Manage system access and permissions",
  tech_10: "Maintain technology standards and controls",
  tech_11: "Manage technology suppliers",
  tech_12: "Deliver system projects and implementations",
  tech_13: "Write system instructions and shared guidance",
  tech_14: "Do other systems or digital work",
  office_01: "Run reception and the front desk",
  office_02: "Welcome and arrange visits",
  office_03: "Handle mail and deliveries",
  office_04: "Order and maintain office supplies",
  office_05: "Arrange building and workplace access",
  office_06: "Issue badges and passes",
  office_07: "Arrange repairs and maintenance",
  office_08: "Arrange office moves and desk changes",
  office_09: "Coordinate workplace suppliers",
  office_10: "Keep workplace health and safety records",
  office_11: "Arrange office equipment and logistics",
  office_12: "Coordinate meeting rooms and office services",
  office_13: "Coordinate local workplace activities",
  office_14: "Do other reception or office work",
};
export const PROCESS_EXAMPLES: Record<string, string> = {
  employee_admin:
    "Employee questions, contracts, letters, records, leave and support tickets.",
  join_move_leave:
    "Hiring, interviews, onboarding, offboarding, country moves and work permits.",
  pay_benefits:
    "Payroll inputs, pay checks, employee benefits and reward support.",
  advice_cases:
    "Manager advice, employee cases (employee relations) and agreed business changes.",
  planning_experience:
    "Staffing plans, performance conversations, development, employee feedback and events.",
  systems_data:
    "People systems, reports, spreadsheets, integrations, automation and digital tools.",
  policies_governance:
    "Policies, local employment requirements, consultation and people decisions.",
  office:
    "Reception, visitors, deliveries, facilities, repairs, office supplies and meeting rooms.",
  suppliers:
    "External services and suppliers beyond the technology and office work above.",
  other_work:
    "Work that does not fit another group, or work you are unsure how to group.",
};
