"use client";
import { useEffect, useRef, useState } from "react";
import { AREAS, WORK_TYPES, COUNTRY_CODES, countryLabel, STEP_LABELS, SYSTEMS, systemLabel, KNOWLEDGE, KNOWLEDGE_LABELS, CHANNELS, CHANNEL_LABELS, FREQUENCIES, FREQUENCY_LABELS, ROLES, ROLE_LABELS, HANDOFFS, HANDOFF_LABELS, availableAreas, allocationTotal, detailCodes, stepError, completionError, type Draft, type Profile, type Detail, type Area } from "@/lib/baseline/model";
import "./style.css";
type Saved = {draft:Draft;campaign:{name:string;privacy:string;closed:boolean};revision:number;progress:number;status:string;updatedAt:string};
async function api<T={revision:number;status:string}>(path:string,body?:unknown):Promise<T>{const response=await fetch("/api/baseline/"+path,{method:body?"POST":"GET",headers:body?{"Content-Type":"application/json"}:undefined,body:body?JSON.stringify(body):undefined,cache:"no-store"});const result=await response.json() as T&{error?:string};if(!response.ok)throw new Error(result.error??"Unable to save. Please try again.");return result;}
function Checks({codes,labels,values,change,max}:{codes:readonly string[];labels?:readonly string[];values:string[];change:(values:string[])=>void;max?:number}){const visible=values.filter(x=>codes.includes(x));return <div className="tb-options">{codes.map((code,i)=><label key={code}><input type="checkbox" checked={values.includes(code)} disabled={!!max&&values.length>=max&&!values.includes(code)} onChange={()=>change(visible.includes(code)?visible.filter(x=>x!==code):[...visible,code])}/><span>{labels?.[i]??code}</span></label>)}</div>;}
function Text({label,value,change,help,max=1500}:{label:string;value:string;change:(value:string)=>void;help?:string;max?:number}){return <label className="tb-field"><span>{label}</span>{help&&<small>{help}</small>}<textarea rows={3} value={value} maxLength={max} onChange={e=>change(e.target.value)}/><small>{value.length} / {max} characters</small></label>;}
function Select({label,value,codes,labels,change}:{label:string;value:string;codes:readonly string[];labels?:readonly string[];change:(value:string)=>void}){return <label className="tb-field"><span>{label}</span><select value={value} onChange={e=>change(e.target.value)}><option value="">Choose an answer</option>{codes.map((code,i)=><option key={code} value={code}>{labels?.[i]??code}</option>)}</select></label>;}
export default function BaselineJourney(){
  const [saved,setSaved]=useState<Saved|null>(null),[draft,setDraft]=useState<Draft|null>(null),[step,setStep]=useState(0),[started,setStarted]=useState(false),[review,setReview]=useState(false),[error,setError]=useState(""),[status,setStatus]=useState("Opening your saved response…"),[busy,setBusy]=useState(false),[search,setSearch]=useState(""),[all,setAll]=useState(false),[custom,setCustom]=useState(""),[customCategory,setCustomCategory]=useState<Area["category"]>("ops"),[systemSearch,setSystemSearch]=useState(""),[systemOther,setSystemOther]=useState("");
  const latest=useRef<Draft|null>(null),revision=useRef(0),queue=useRef<Promise<void>>(Promise.resolve()),lastSaved=useRef(""),progress=useRef(0),conflict=useRef(false),heading=useRef<HTMLHeadingElement>(null);
  const change=(next:Draft)=>{latest.current=next;setDraft(next);setStatus("Changes waiting to save…");};
  function save(next=latest.current,stage?:number){
    if(!next||conflict.current)return Promise.reject(new Error("Reload your saved response before continuing."));
    const snapshot=structuredClone(next);const serialized=JSON.stringify(snapshot);
    queue.current=queue.current.catch(()=>{}).then(async()=>{const targetStage=stage??progress.current;if(serialized===lastSaved.current&&targetStage===progress.current)return;try{setStatus("Saving…");const result=await api("save",{draft:snapshot,revision:revision.current,progress:targetStage});revision.current=result.revision;progress.current=targetStage;lastSaved.current=serialized;setStatus(latest.current&&JSON.stringify(latest.current)===serialized?"Saved securely":"Changes waiting to save…");setError("");}catch(e){const message=e instanceof Error?e.message:"Not saved. Keep this page open and retry.";if(message.includes("newer save")||message.includes("already submitted"))conflict.current=true;setStatus("Not saved — keep this page open");setError(message);throw e;}});return queue.current;
  }
  useEffect(()=>{let live=true;async function open(){try{const token=window.location.hash.slice(1);if(token){window.history.replaceState(null,"",window.location.pathname);await api("access",{token});}const response=await api<Saved>("response");if(!live)return;setSaved(response);setDraft(response.draft);latest.current=response.draft;revision.current=response.revision;progress.current=response.progress;lastSaved.current=JSON.stringify(response.draft);setStep(Math.min(response.progress,7));setStarted(response.draft.privacyAcknowledged);setStatus("Saved securely");}catch(e){if(live){setError(e instanceof Error?e.message:"Unable to open this assessment.");setStatus("");}}}void open();return()=>{live=false;};},[]);
  useEffect(()=>{if(!draft||!started||saved?.status==="completed"||saved?.campaign.closed)return;const timer=setTimeout(()=>{void save().catch(()=>{});},650);return()=>clearTimeout(timer);/* save uses current refs; never capture an obsolete revision. */
  },[draft,started,saved?.status,saved?.campaign.closed]);
  useEffect(()=>{const leave=(event:BeforeUnloadEvent)=>{if(latest.current&&JSON.stringify(latest.current)!==lastSaved.current){event.preventDefault();event.returnValue="";}};const online=()=>{if(latest.current&&JSON.stringify(latest.current)!==lastSaved.current)void save().catch(()=>{});};window.addEventListener("beforeunload",leave);window.addEventListener("online",online);return()=>{window.removeEventListener("beforeunload",leave);window.removeEventListener("online",online);};},[]);
  useEffect(()=>{heading.current?.focus();},[step,review]);
  async function move(forward:boolean){if(!draft)return;const message=forward?stepError(draft,step):null;if(message){setError(message);return;}setBusy(true);try{await save(draft,forward?Math.min(step+1,8):Math.max(step-1,0));if(forward&&step===7)setReview(true);else setStep(s=>forward?s+1:s-1);setError("");setSearch("");}catch{}finally{setBusy(false);}}
  async function finish(){if(!draft)return;const message=completionError(draft);if(message){setError(message);return;}setBusy(true);try{await save();const result=await api("submit",{draft:latest.current,revision:revision.current,progress:8});revision.current=result.revision;lastSaved.current=JSON.stringify(latest.current);setSaved(s=>s?{...s,status:"completed"}:s);setStatus("Submitted securely");setError("");}catch(e){setError(e instanceof Error?e.message:"Unable to submit.");}finally{setBusy(false);}}
  async function leave(){setBusy(true);try{if(draft&&saved?.status!=="completed")await save();await api("logout",{});window.location.reload();}catch{}finally{setBusy(false);}}
  const updateProfile=(key:keyof Profile,value:Profile[keyof Profile])=>draft&&change({...draft,profile:{...draft.profile,[key]:value}});
  const updateDetail=(code:string,key:keyof Detail,value:Detail[keyof Detail])=>draft&&change({...draft,details:{...draft.details,[code]:{...(draft.details[code]??{description:"",frequency:"",role:"",handoffs:[],other:""}),[key]:value}}});
  const chooseArea=(code:string)=>{if(!draft)return;if(draft.areas.includes(code)){const allocation={...draft.allocation},details={...draft.details};delete allocation[code];delete details[code];change({...draft,areas:draft.areas.filter(x=>x!==code),important:draft.important.filter(x=>x!==code),allocation,details});}else change({...draft,areas:[...draft.areas,code]});};
  const selected=draft?[...AREAS,...draft.customAreas].filter(a=>draft.areas.includes(a.code)):[];
  return <main className="tb-shell"><header className="tb-header"><span>team.blue · Current work baseline</span><p>Describe what you do today. Help us understand the work.</p></header>
    {error&&<div role="alert" className="tb-error">{error}{conflict.current&&<button onClick={()=>window.location.reload()}>Reload saved response</button>}</div>}
    {!saved||!draft?<section className="tb-card"><h1>Current work baseline</h1><p>{status||"Use the private link in your invitation email. If it has expired, ask the organiser for a new one."}</p></section>:saved.status==="completed"?<section className="tb-card"><h1>Thank you. Your response is complete.</h1><p>Your answers have been saved. You do not need to submit them again.</p><p>If you need to correct an answer, contact the campaign organiser.</p><button onClick={leave}>Close secure session</button></section>:<>
      {!started?<section className="tb-card"><h1>{saved.campaign.name}</h1><p className="tb-estimate">About 20–25 minutes · Save and return at any time</p><h2>Before you start</h2><p>{saved.campaign.privacy}</p><p>There are eight short steps. Use selections where possible. Approximate answers are useful.</p><label className="tb-check"><input type="checkbox" checked={draft.privacyAcknowledged} onChange={e=>change({...draft,privacyAcknowledged:e.target.checked})}/>I have read and understand this data-use statement.</label><button disabled={!draft.privacyAcknowledged||saved.campaign.closed} onClick={()=>setStarted(true)}>Start assessment</button></section>:<>
        <nav aria-label="Assessment progress" className="tb-progress"><span>Step {step+1} of 8</span><progress max={8} value={review?8:step+1}/><span>{STEP_LABELS[step]}</span></nav>
        <div role="status" aria-live="polite" className="tb-save">{status} {status.startsWith("Not saved")&&<button onClick={()=>void save().catch(()=>{})}>Retry save</button>}</div>
        <section className="tb-card"><h1 ref={heading} tabIndex={-1}>{review?"Review and submit":STEP_LABELS[step]}</h1>
        {saved.campaign.closed&&<p role="alert">This campaign is closed. You can see your saved answers, but you cannot change them.</p>}
        <fieldset disabled={busy||saved.campaign.closed||conflict.current}>
        {review?<><p>Please check your answers before submitting. You can go back to any step.</p><dl><dt>Current role</dt><dd>{draft.profile.name} · {draft.profile.job_title}</dd><dt>Time allocation</dt><dd>{allocationTotal(draft)}% in total</dd><dt>Your main work areas</dt><dd>{selected.map(a=>a.label).join("; ")}</dd></dl><div className="tb-review">{STEP_LABELS.map((label,i)=><button key={label} onClick={()=>{setReview(false);setStep(i);}}>{i+1}. {label}</button>)}</div><p>Submitting finishes your response. These answers describe current work, not your future role.</p></>:<>
        {step===0&&<><p>Please confirm your current details. Do not use a proposed future title.</p>{(["name","job_title","region","entity"] as const).map(key=><label className="tb-field" key={key}><span>{{name:"Name",job_title:"Current job title",region:"Region (if used)",entity:"Employing business / entity (if known)"}[key]}</span><input value={draft.profile[key]} maxLength={250} onChange={e=>updateProfile(key,e.target.value)}/></label>)}<label className="tb-field"><span>Email from your invitation</span><input value={draft.profile.email} readOnly/><small>Ask the organiser if this needs changing.</small></label><Select label="Country where you are primarily based" value={draft.profile.country} codes={COUNTRY_CODES} labels={COUNTRY_CODES.map(countryLabel)} change={v=>updateProfile("country",v)}/><Select label="Which area best describes your current work?" value={draft.profile.work_type} codes={WORK_TYPES.map(x=>x[0])} labels={WORK_TYPES.map(x=>x[1])} change={v=>updateProfile("work_type",v)}/><Select label="Do you manage people?" value={draft.profile.manages_people} codes={["yes","no","not_sure"]} labels={["Yes","No","Not sure"]} change={v=>updateProfile("manages_people",v)}/>{draft.profile.manages_people==="yes"&&<label className="tb-field"><span>About how many people report directly to you?</span><input type="number" min={0} max={1000} value={draft.profile.direct_reports} onChange={e=>updateProfile("direct_reports",e.target.value)}/></label>}<h2>Which countries or areas do you regularly support?</h2><p>Support means people or businesses your work serves. You can choose more than one.</p><Checks codes={["countries","regional","group","business","other","not_sure"]} labels={["One or more countries","Regional","Group / all team.blue","A specific business or division","Other","Not sure"]} values={draft.profile.support_levels} change={v=>updateProfile("support_levels",v)}/>{draft.profile.support_levels.includes("countries")&&<details open><summary>Choose supported countries</summary><Checks codes={COUNTRY_CODES} labels={COUNTRY_CODES.map(countryLabel)} values={draft.profile.support_countries} change={v=>updateProfile("support_countries",v)}/></details>}<Text label="Region, business or other support area (if relevant)" value={draft.profile.support_other} change={v=>updateProfile("support_other",v)} max={500}/></>}
        {step===1&&<><p>Choose the areas where you currently spend meaningful time. Your title does not limit your choices.</p><label className="tb-field"><span>Search all work areas</span><input type="search" value={search} onChange={e=>setSearch(e.target.value)}/></label><label className="tb-check"><input type="checkbox" checked={all} onChange={e=>setAll(e.target.checked)}/>Show work across all categories</label><Checks codes={[...availableAreas(draft.profile.work_type,all,search),...draft.customAreas].map(a=>a.code)} labels={[...availableAreas(draft.profile.work_type,all,search),...draft.customAreas].map(a=>a.label)} values={draft.areas} max={40} change={values=>{const visible=new Set([...availableAreas(draft.profile.work_type,all,search),...draft.customAreas].map(a=>a.code));const keep=draft.areas.filter(x=>!visible.has(x));const next=[...keep,...values];const allocation=Object.fromEntries(Object.entries(draft.allocation).filter(([code])=>next.includes(code))),details=Object.fromEntries(Object.entries(draft.details).filter(([code])=>next.includes(code)));change({...draft,areas:next,allocation,details,important:draft.important.filter(x=>next.includes(x))});}}/><label className="tb-field"><span>Add another work area (up to six)</span><input value={custom} maxLength={120} onChange={e=>setCustom(e.target.value)}/></label><Select label="Category for your added work area" codes={["ops","bp","tech","office"]} labels={["People Operations","People Business Partnering","People Technology","Reception / facilities / office operations"]} value={customCategory} change={v=>setCustomCategory(v as Area["category"])}/><button disabled={!custom.trim()||draft.customAreas.length>=6||draft.areas.length>=40} onClick={()=>{const category=customCategory;const area:Area={code:"custom_"+crypto.randomUUID(),label:custom.trim(),category,example:"Briefly describe your current work."};change({...draft,customAreas:[...draft.customAreas,area],areas:[...draft.areas,area.code]});setCustom("");}}>Add work area</button><p>{draft.areas.length} areas selected</p><div className="tb-tags">{selected.map(a=><button key={a.code} onClick={()=>chooseArea(a.code)} aria-label={`Remove ${a.label}`}>{a.label} ×</button>)}</div></>}
        {step===2&&<><p>In a typical month, about how much of your working time is spent on each area?</p><p>This does not need to be exact. Think about an average month. If something normally takes about one day each week, you might enter 20%.</p><div className="tb-total" aria-live="polite">Total: {allocationTotal(draft)}% <progress max={100} value={Math.min(allocationTotal(draft),100)}/><small>Aim for 100%. Between 98% and 102% is accepted.</small></div>{selected.map(a=><label className="tb-field" key={a.code}><span>{a.label}</span><div className="tb-percentage"><input aria-label={`${a.label} percentage`} type="number" inputMode="decimal" min={0} max={100} step={0.5} value={draft.allocation[a.code]??""} onChange={e=>{const allocation={...draft.allocation};if(e.target.value==="")delete allocation[a.code];else allocation[a.code]=Number(e.target.value);change({...draft,allocation});}}/><span>%</span></div></label>)}</>}
        {step===3&&<><p>We ask for a little more detail about your three largest work areas. Add up to two other areas if they are important.</p><details><summary>Choose additional important areas</summary><Checks codes={draft.areas.filter(x=>!detailCodes({...draft,important:[]}).includes(x))} labels={draft.areas.filter(x=>!detailCodes({...draft,important:[]}).includes(x)).map(code=>selected.find(a=>a.code===code)!.label)} values={draft.important} max={2} change={v=>change({...draft,important:v})}/></details>{detailCodes(draft).map(code=>{const a=selected.find(a=>a.code===code)!;const d=draft.details[code]??{description:"",frequency:"",role:"",handoffs:[],other:""};return <article className="tb-detail" key={code}><h2>{a.label}</h2><Text label="What do you normally do in this area?" help={a.example+" Do not include individual employee cases."} value={d.description} max={700} change={v=>updateDetail(code,"description",v)}/><Select label="How often do you normally do this work?" codes={FREQUENCIES} labels={FREQUENCY_LABELS} value={d.frequency} change={v=>updateDetail(code,"frequency",v)}/><Select label="Which best describes your role in this work?" codes={ROLES} labels={ROLE_LABELS} value={d.role} change={v=>updateDetail(code,"role",v)}/><details><summary>What does responsibility for the final result mean?</summary><p>You are the person expected to make sure this work is finished correctly. A process owner is responsible for how a whole process works; this may be a different person.</p></details><h3>Who do you normally work with or hand this work to/from?</h3><p>A hand-off is work or information passed between people or teams.</p><Checks codes={HANDOFFS} labels={HANDOFF_LABELS} values={d.handoffs} change={v=>updateDetail(code,"handoffs",v)}/><Text label="Other team or important hand-off (optional)" value={d.other} max={300} change={v=>updateDetail(code,"other",v)}/></article>;})}</>}
        {step===4&&<><p>Is there important work you do only at certain times of the year or only when something happens?</p><p>For example: annual pay activity, audits, office moves, restructures, major employee cases, annual reporting or system projects. Describe the type of work, not individual cases.</p><Select label="Do you have important occasional work?" codes={["yes","no","not_sure"]} labels={["Yes","No","Not sure"]} value={draft.cyclical.answer} change={v=>change({...draft,cyclical:{answer:v,text:v==="yes"?draft.cyclical.text:""}})}/>{draft.cyclical.answer==="yes"&&<Text label="Briefly describe this work" value={draft.cyclical.text} max={1000} change={v=>change({...draft,cyclical:{...draft.cyclical,text:v}})}/>}</>}
        {step===5&&<><h2>Which systems or tools do you use regularly for your work?</h2><label className="tb-field"><span>Search systems</span><input type="search" value={systemSearch} onChange={e=>setSystemSearch(e.target.value)}/></label><Checks codes={[...new Set([...SYSTEMS,...draft.systems])].filter(s=>systemLabel(s).toLowerCase().includes(systemSearch.toLowerCase()))} labels={[...new Set([...SYSTEMS,...draft.systems])].filter(s=>systemLabel(s).toLowerCase().includes(systemSearch.toLowerCase())).map(systemLabel)} values={draft.systems} change={v=>{const visible=new Set([...SYSTEMS,...draft.systems].filter(s=>s.toLowerCase().includes(systemSearch.toLowerCase())));change({...draft,systems:[...draft.systems.filter(s=>!visible.has(s)),...v]});}}/><label className="tb-field"><span>Add another system or tool</span><input value={systemOther} maxLength={120} onChange={e=>setSystemOther(e.target.value)}/></label><button disabled={!systemOther.trim()} onClick={()=>{change({...draft,systems:[...new Set([...draft.systems,systemOther.trim()])]});setSystemOther("");}}>Add system</button><h2>What knowledge or experience do colleagues rely on you for?</h2><p>This describes current knowledge. It does not rate your capability or performance.</p><Checks codes={KNOWLEDGE} labels={KNOWLEDGE_LABELS} values={draft.knowledge} change={v=>change({...draft,knowledge:v})}/><Text label="Specific country, business or specialist knowledge (optional)" value={draft.knowledgeOther} change={v=>change({...draft,knowledgeOther:v})}/></>}
        {step===6&&<><p>Choose the main three ways work reaches you. Fewer than three is fine.</p><Checks codes={CHANNELS} labels={CHANNEL_LABELS} values={draft.channels} max={3} change={v=>change({...draft,channels:v})}/><Text label="Other way work reaches you (optional)" value={draft.channelOther} change={v=>change({...draft,channelOther:v})}/></>}
        {step===7&&<><Text label="Which parts of your work take more time or manual effort than they should? (optional)" help="For example: re-entering information, spreadsheets, repeated checking, waiting for information, chasing approvals or doing the same task in more than one system." value={draft.friction} change={v=>change({...draft,friction:v})}/><Text label="What works particularly well today and should we make sure we keep? (optional)" value={draft.strengths} change={v=>change({...draft,strengths:v})}/><Text label="Is there anything important about your current work that we have not asked? (optional)" value={draft.anything} change={v=>change({...draft,anything:v})}/></>}
        </>}
        <footer className="tb-actions">{review?<><button onClick={()=>setReview(false)}>Back to answers</button><button className="tb-primary" onClick={finish}>Submit response</button></>:<>{step>0&&<button onClick={()=>void move(false)}>Back</button>}<button className="tb-primary" onClick={()=>void move(true)}>{step===7?"Review answers":"Save and continue"}</button></>}</footer></fieldset></section><button disabled={busy} className="tb-leave" onClick={leave}>Save and leave — return using your invitation email</button></>}
      </>}
    <footer className="tb-footnote">Current work only · No performance rating · Your private response</footer>
  </main>;
}
